CREATE TABLE SEQ_SENT_EVENT
(
    ID           NUMBER(20) not null,
    EXPENSE_ID   NUMBER(20),
    PROCESSED    NUMBER(1),
    UPDATED_TIME TIMESTAMP,
    CREATED_TIME TIMESTAMP,
)
    /
CREATE SEQUENCE SEQ_SENT_EVENT INCREMENT BY 10 cache 1000