CREATE TABLE TBL_MONTHLY_REPORT
(
    ID                NUMBER(20) not null,
    CATEGORY_ID       NUMBER(20),
    CUMULATIVE_AMOUNT NUMBER(12, 2),
    ALERT             NVARCHAR2(1000),
    FROM_DATE         TIMESTAMP,
    TO_DATE           TIMESTAMP,
    UPDATED_TIME      TIMESTAMP,
    CREATED_TIME      TIMESTAMP
)
/
CREATE SEQUENCE SEQ_MNT_RPT INCREMENT BY 10 cache 1000